Milestone 3: Events
AkashaRojee/math-magicians pull request #3
Opened 2021-08-13 21:46 UTC by AkashaRojee

Hello!

I implemented the event handlers to make the calculator work with the provided logic files.

Things done:

- Add provided logic files
- Implement click event handler for Key to register which calculator button is pressed
- Lift state up from Key to Calculator
- Set state to an object as required by calculate.js: `{total, next, operation}`
- Use custom object (DataObject) to store object
- Pass state as props to Display
- Construct string to display using values from data object
- Modify operate.js to cater for division by zero
- Modify calculate.js to cater for resetting display
- Fix linter errors
- Update README
- Deploy from branch

Please, review the code.

Thanks!

2021-08-13 22:14 UTC, henatan99 requested changes
Hi @AkashaRojee , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 22:14 UTC, henatan99 commented on src/components/Calculator.js
> +      dataObject: { ...state.dataObject, ...calculate(state.dataObject, key) },
- [ ] When an operator is clicked twice the app throws an error on the browser. Kindly incorporate error handling methods/conditions. 
![image](https://user-images.githubusercontent.com/64894927/129422725-8d4a138c-ba4d-4d79-bd5f-38aa0aa832e0.png)
- [ ] When a number is divided by zero, your app returns a result which is `0`. But it should return some message like `Infinity`. Kindly handle this behavior.

2021-08-13 22:36 UTC, AkashaRojee commented
Hi @henatan99,

Thanks for the feedback.

I implemented the changes.

Things done:

- Prevent operator buttons from being clicked consecutively

- Display "Undefined" as result of division by 0

Please, review the code.

Thanks!

2021-08-13 22:56 UTC, henatan99 approved these changes
Hi @AkashaRojee , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-14 08:48 UTC, closed without merging

2021-08-14 08:49 UTC, AkashaRojee commented
Hi @henatan99,

Thanks!